export enum soilEnum {
	SABLE = "SABLE",
	SABLE_TERREAU = "SABLE_TERREAU",
	TERREAU = "TERREAU",
	TERREAU_ARGILE = "TERREAU_ARGILE",
	ARGILE = "ARGILE",
	CRAIE = "CRAIE",
	LIMON_SABLEUX = "LIMON_SABLEUX",
	LIMON_FIN = "LIMON_FIN",
	LIMON_ARGILO_SABLEUX = "LIMON_ARGILO_SABLEUX",
	ARGILE_SABLEUX = "ARGILE_SABLEUX",
	ARGILE_LIMONEUSE = "ARGILE_LIMONEUSE",
}

export const soilList: soilEnum[] = Object.values(soilEnum);
