#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
nx affected --target=format --all ||
(
    echo 'Prettier check Failed.';
    false;
)

echo '✅ Your code style is looking good, checking Typescript now ...'
# Check tsconfig standards
nx affected --target=tsc --all ||
(
    echo 'Typescript checks failed. Make the changes required above.'
    false;
)

echo '✅ No Typescript error, congrats ! Checking ESLint'

# Check ESLint Standards
nx affected --target=lint --all ||
(
        echo 'ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# If everything passes... Now we can commit
echo '✅ Everything looks perfect. Commiting ...'
